// All 50 games with metadata
export const GAMES = [
  { id:'battle_royale',    name:'Battle Royale',    icon:'sword',     minPlayers:2, maxPlayers:4, tags:['action','pvp'],      description:'Last one standing wins!' },
  { id:'soccer',           name:'Soccer',           icon:'soccer',    minPlayers:2, maxPlayers:4, tags:['sports','ball'],     description:'Score goals, block shots!' },
  { id:'basketball',       name:'Basketball',       icon:'hoop',      minPlayers:2, maxPlayers:4, tags:['sports','ball'],     description:'Most hoops wins!' },
  { id:'car_racing',       name:'Car Racing',       icon:'car',       minPlayers:2, maxPlayers:4, tags:['racing','speed'],    description:'First to the finish line!' },
  { id:'sword_fight',      name:'Sword Fight',      icon:'sword2',    minPlayers:2, maxPlayers:4, tags:['action','pvp'],      description:'Duel to the death!' },
  { id:'bow_arrow',        name:'Bow & Arrow',      icon:'bow',       minPlayers:2, maxPlayers:4, tags:['action','skill'],    description:'Take aim and fire!' },
  { id:'sumo',             name:'Sumo',             icon:'sumo',      minPlayers:2, maxPlayers:4, tags:['action','push'],     description:'Push opponents out of the ring!' },
  { id:'volleyball',       name:'Volleyball',       icon:'vball',     minPlayers:2, maxPlayers:4, tags:['sports','ball'],     description:'Spike it over the net!' },
  { id:'tank_battle',      name:'Tank Battle',      icon:'tank',      minPlayers:2, maxPlayers:4, tags:['action','shoot'],    description:'Destroy enemy tanks!' },
  { id:'snowball_fight',   name:'Snowball Fight',   icon:'snow',      minPlayers:2, maxPlayers:4, tags:['action','fun'],      description:'Pelt your friends with snow!' },
  { id:'tug_of_war',       name:'Tug of War',       icon:'rope',      minPlayers:2, maxPlayers:4, tags:['strength','fun'],    description:'Pull the rope your way!' },
  { id:'bomb_game',        name:'Bomb Game',        icon:'bomb',      minPlayers:2, maxPlayers:4, tags:['action','strategy'], description:'Bomberman-style arena battle!' },
  { id:'dodgeball',        name:'Dodgeball',        icon:'dodge',     minPlayers:2, maxPlayers:4, tags:['sports','speed'],    description:'Dodge, dip, duck, dive!' },
  { id:'ice_slide',        name:'Ice Slide',        icon:'sled',      minPlayers:2, maxPlayers:4, tags:['racing','fun'],      description:'Slide down icy slopes!' },
  { id:'lava_jump',        name:'Lava Jump',        icon:'lava',      minPlayers:2, maxPlayers:4, tags:['platform','skill'],  description:'Don\'t touch the lava!' },
  { id:'platformer_race',  name:'Platformer Race',  icon:'jump',      minPlayers:2, maxPlayers:4, tags:['platform','racing'], description:'Race to the finish!' },
  { id:'coin_collector',   name:'Coin Collector',   icon:'coin',      minPlayers:2, maxPlayers:4, tags:['collect','fun'],     description:'Grab the most coins!' },
  { id:'color_flood',      name:'Color Flood',      icon:'paint',     minPlayers:2, maxPlayers:4, tags:['puzzle','strategy'], description:'Flood the board with your color!' },
  { id:'snake',            name:'Snake',            icon:'snake',     minPlayers:2, maxPlayers:4, tags:['classic','skill'],   description:'Grow longest without crashing!' },
  { id:'pong',             name:'Pong',             icon:'pong',      minPlayers:2, maxPlayers:2, tags:['classic','sports'],  description:'Classic table tennis!' },
  { id:'air_hockey',       name:'Air Hockey',       icon:'puck',      minPlayers:2, maxPlayers:2, tags:['classic','speed'],   description:'Slide the puck, score goals!' },
  { id:'mini_golf',        name:'Mini Golf',        icon:'golf',      minPlayers:2, maxPlayers:4, tags:['sports','skill'],    description:'Putt in the fewest shots!' },
  { id:'fishing',          name:'Fishing',          icon:'fish',      minPlayers:2, maxPlayers:4, tags:['chill','skill'],     description:'Catch the biggest fish!' },
  { id:'cooking_battle',   name:'Cooking Battle',   icon:'cook',      minPlayers:2, maxPlayers:4, tags:['fun','speed'],       description:'Cook orders fastest!' },
  { id:'gardening_race',   name:'Gardening Race',   icon:'flower',    minPlayers:2, maxPlayers:4, tags:['chill','race'],      description:'Grow your garden fastest!' },
  { id:'treasure_hunt',    name:'Treasure Hunt',    icon:'chest',     minPlayers:2, maxPlayers:4, tags:['explore','fun'],     description:'Find the buried treasure!' },
  { id:'maze_race',        name:'Maze Race',        icon:'maze',      minPlayers:2, maxPlayers:4, tags:['puzzle','racing'],   description:'Navigate the maze first!' },
  { id:'bubble_shooter',   name:'Bubble Shooter',   icon:'bubble',    minPlayers:2, maxPlayers:4, tags:['puzzle','skill'],    description:'Pop bubble clusters!' },
  { id:'tower_defense',    name:'Tower Defense',    icon:'tower',     minPlayers:2, maxPlayers:4, tags:['strategy','build'],  description:'Defend your base!' },
  { id:'card_battle',      name:'Card Battle',      icon:'card',      minPlayers:2, maxPlayers:4, tags:['strategy','card'],   description:'Outsmart your rivals!' },
  { id:'cannon_ball',      name:'Cannon Ball',      icon:'cannon',    minPlayers:2, maxPlayers:4, tags:['action','skill'],    description:'Fire your cannon!' },
  { id:'king_of_hill',     name:'King of the Hill', icon:'crown',     minPlayers:2, maxPlayers:4, tags:['action','zone'],     description:'Hold the top the longest!' },
  { id:'capture_flag',     name:'Capture the Flag', icon:'flag',      minPlayers:2, maxPlayers:4, tags:['team','strategy'],   description:'Steal the enemy flag!' },
  { id:'ghost_chase',      name:'Ghost Chase',      icon:'ghost',     minPlayers:2, maxPlayers:4, tags:['fun','chase'],       description:'Run from the ghost!' },
  { id:'zombie_survival',  name:'Zombie Survival',  icon:'zombie',    minPlayers:2, maxPlayers:4, tags:['survival','action'], description:'Survive the zombie horde!' },
  { id:'space_race',       name:'Space Race',       icon:'rocket',    minPlayers:2, maxPlayers:4, tags:['racing','scifi'],    description:'Race through the cosmos!' },
  { id:'pinball',          name:'Pinball',          icon:'pinball',   minPlayers:2, maxPlayers:4, tags:['classic','skill'],   description:'Keep the ball alive!' },
  { id:'breakout',         name:'Breakout',         icon:'brick',     minPlayers:2, maxPlayers:4, tags:['classic','skill'],   description:'Break all the bricks!' },
  { id:'asteroid_shooter', name:'Asteroid Shooter', icon:'asteroid',  minPlayers:2, maxPlayers:4, tags:['action','shoot'],    description:'Destroy the asteroids!' },
  { id:'rps_battle',       name:'Rock Paper Scissors',icon:'rps',     minPlayers:2, maxPlayers:4, tags:['classic','fun'],     description:'RPS with power-ups!' },
  { id:'billiards',        name:'Billiards',        icon:'billiard',  minPlayers:2, maxPlayers:2, tags:['classic','skill'],   description:'Pot balls with precision!' },
  { id:'darts',            name:'Darts',            icon:'dart',      minPlayers:2, maxPlayers:4, tags:['skill','sports'],    description:'Highest score on the board!' },
  { id:'bowling',          name:'Bowling',          icon:'bowling',   minPlayers:2, maxPlayers:4, tags:['sports','skill'],    description:'Strike for the highest score!' },
  { id:'farm_race',        name:'Farm Race',        icon:'tractor',   minPlayers:2, maxPlayers:4, tags:['fun','race'],        description:'Harvest crops the fastest!' },
  { id:'ice_hockey',       name:'Ice Hockey',       icon:'hockey',    minPlayers:2, maxPlayers:4, tags:['sports','speed'],    description:'Score on the icy rink!' },
  { id:'ninja_dash',       name:'Ninja Dash',       icon:'ninja',     minPlayers:2, maxPlayers:4, tags:['action','platform'], description:'Dash across rooftops!' },
  { id:'catapult_wars',    name:'Catapult Wars',    icon:'catapult',  minPlayers:2, maxPlayers:4, tags:['strategy','destroy'],description:'Smash enemy castles!' },
  { id:'color_paint',      name:'Color Paint',      icon:'brush',     minPlayers:2, maxPlayers:4, tags:['creative','fun'],    description:'Paint the most territory!' },
  { id:'penguin_slide',    name:'Penguin Slide',    icon:'penguin',   minPlayers:2, maxPlayers:4, tags:['fun','racing'],      description:'Slide & collect fish!' },
  { id:'dance_off',        name:'Dance Off',        icon:'music',     minPlayers:2, maxPlayers:6, tags:['rhythm','fun'],      description:'Hit the rhythm, score big!' },
];
